[workspace]
members = [
    "a-get-node-info",
    "b-send-data",
    "c-get-transaction-hash",
    "d-fetch-data",
    "e-generate-address",
    "f-send-tokens",
    "g-check-balance",
    "h-streams",
    "h-streams-publish",
    "h-streams-subscribe"
]
