[package]
name = "h-streams-subscribe"
version = "0.1.0"
authors = ["huhn <huhn@einfachIOTA.de>", "you", ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]