[package]
name = "examples"
version = "0.1.0"
authors = ["rckey <private.richardk@gmail.com>", "huhn <huhn@einfachIOTA.de>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
iota-core = "0.2.0-alpha.2"
iota-conversion =  "0.5.0"
smol = {version = "=0.1.7", features = ["tokio02"] }
smol-potat = "0.3.1"

[[example]]
name = "00_get_node_info"
path = "00_get_node_info.rs"

[[example]]
name = "01_send_data"
path = "01_send_data.rs"

[[example]]
name = "02_fetch_data"
path = "02_fetch_data.rs"

[[example]]
name = "03_get_new_address"
path = "03_get_new_address.rs"

[[example]]
name = "04_check_balance"
path = "04_check_balance.rs"

[[example]]
name = "05_send_tokens"
path = "05_send_tokens.rs"