[package]
name = "2-send-data"
version = "0.1.0"
authors = ["rckey <private.richardk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iota-lib-rs = "0.4.1"
